-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 15:51:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema decbot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema decbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decbot` DEFAULT CHARACTER SET utf8mb3 ;
USE `decbot` ;

-- -----------------------------------------------------
-- Table `decbot`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decbot`.`links` (
  `name` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL,
  `link` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `decbot`.`privileged_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decbot`.`privileged_users` (
  `user_id` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL,
  `protocol` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`user_id`, `protocol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `decbot`.`quotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decbot`.`quotes` (
  `timestamp` TIMESTAMP NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `addedby` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL,
  `quote` VARCHAR(1500) CHARACTER SET 'utf8mb3' NOT NULL,
  `active` BIT(1) NOT NULL DEFAULT b'1',
  `ScoreUp` INT NULL DEFAULT '0',
  `ScoreDown` INT NULL DEFAULT '0',
  `deletedby` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `decbot`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decbot`.`scores` (
  `name` VARCHAR(500) NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `decbot`.`scores_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decbot`.`scores_log` (
  `name` VARCHAR(500) CHARACTER SET 'utf8mb3' NOT NULL,
  `change` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
